/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package frames;
import Database.initializeDatabase;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author onatu
 */
public class loginScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginScreen.class.getName());
    shoppingScreen shopping;
    Connection conn;
    /**
     * Creates new form loginScreen
     */
    public loginScreen() {
        initComponents();
        conn=initializeDatabase.connect();
        if(initializeDatabase.getConnectionCount()==0)
            System.exit(0);
        this.setLocation(400,200);
        shopping = new shoppingScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LoginScreenText = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        customerButton = new javax.swing.JRadioButton();
        adminButton = new javax.swing.JRadioButton();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginScreenText.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        LoginScreenText.setForeground(new java.awt.Color(255, 51, 204));
        LoginScreenText.setText("LOGIN SCREEN");

        emailField.setText("e-mail");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addActionListener(this::emailFieldActionPerformed);

        passwordField.setText("Password");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });

        buttonGroup1.add(customerButton);
        customerButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        customerButton.setForeground(new java.awt.Color(255, 51, 255));
        customerButton.setText("Customer");
        customerButton.addActionListener(this::customerButtonActionPerformed);

        buttonGroup1.add(adminButton);
        adminButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 51, 255));
        adminButton.setText("Admin");
        adminButton.setMaximumSize(new java.awt.Dimension(53, 20));
        adminButton.setPreferredSize(new java.awt.Dimension(53, 20));
        adminButton.addActionListener(this::adminButtonActionPerformed);

        loginButton.setText("Login");
        loginButton.addActionListener(this::loginButtonActionPerformed);

        registerButton.setText("Register");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(LoginScreenText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(loginButton)
                        .addGap(34, 34, 34)
                        .addComponent(registerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(customerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(LoginScreenText)
                .addGap(100, 100, 100)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerButton)
                    .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(registerButton))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        String text=emailField.getText();
        if(text.equals("e-mail")){
        emailField.setText("");
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        registerButton.setEnabled(false);
    }//GEN-LAST:event_adminButtonActionPerformed

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
if(emailField.getText().equals(""))
    emailField.setText("e-mail");
    }//GEN-LAST:event_emailFieldFocusLost

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
         String text=passwordField.getText();
        if(text.equals("Password")){
        passwordField.setText("");
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if(passwordField.getText().equals(""))
    passwordField.setText("Password");
    }//GEN-LAST:event_passwordFieldFocusLost

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
       registerButton.setEnabled(true);
    }//GEN-LAST:event_customerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
      String username=emailField.getText();
      String password = passwordField.getText();
        
      String sqlQuery = "select * from Users where email=? AND password=?";
      
        try(PreparedStatement ps = conn.prepareStatement(sqlQuery)){
        
            ps.setString(1, username);
            ps.setString(2, password);
            
        try(ResultSet rs=ps.executeQuery()){
        
            if(rs.next())
            {
            //IMPORTANT Frame switch occurs.
            if(adminButton.isSelected()&&rs.getString("role").toLowerCase().equals("admin")){
                    System.out.println("Login was successful.");
            JOptionPane.showMessageDialog(this, "The login is successful!", "Logged in", JOptionPane.INFORMATION_MESSAGE);
                   }
                   else if(customerButton.isSelected()&&rs.getString("role").toLowerCase().equals("customer")) {
                       System.out.println("Login was successful.");
                       JOptionPane.showMessageDialog(this, "The login is successful!", "Logged in", JOptionPane.INFORMATION_MESSAGE);
                   shopping.setVisible(true);
                   this.dispose();
                   }
                   else{
            javax.swing.JOptionPane.showMessageDialog(this, 
                        "Something is wrong!", 
                        "Unsuccessfull login", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
            }
            else{
            javax.swing.JOptionPane.showMessageDialog(this, 
                        "Something is wrong!", 
                        "Unsuccessfull login", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        
        }
        catch(SQLException e){
        e.printStackTrace();
        }
        
        
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loginScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginScreenText;
    private javax.swing.JRadioButton adminButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton customerButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
