/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import Database.User;
import java.sql.*;
/**
 *
 * @author onatu
 */
public class ordersScreenCustomer extends javax.swing.JFrame implements OrderView {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ordersScreenCustomer.class.getName());
    Connection conn;
    int userID;
    shoppingScreen shoppingScreen;
    
    /**
     * Creates new form ordersScreenCustomer
     */
    public ordersScreenCustomer(Connection conn,shoppingScreen ss) {
        initComponents();
        userID=User.getUserID();
        this.conn=conn;
        shoppingScreen=ss;
        this.setLocation(shoppingScreen.getLocation());
        this.setSize(468,420);
        getOrdersOnTable();
    }
    
    @Override
    public void getOrdersOnTable() {

        String sql = "SELECT orderID, orderDate, totalAmount, status FROM orders WHERE userID = ?";

        try(PreparedStatement ps = conn.prepareStatement(sql)){

            ps.setString(1, String.valueOf(userID));
            try(ResultSet rs = ps.executeQuery()){
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
                model.setRowCount(0); // Clear existing rows

                while(rs.next()){
                    int orderID = rs.getInt("orderID");
                    Date orderDate = rs.getDate("orderDate");
                    double totalAmount = rs.getDouble("totalAmount");
                    String status = rs.getString("status");

                    model.addRow(new Object[]{orderID, orderDate, totalAmount, status});
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Order Date", "totalAmount", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(50, 100));

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);
        jPanel1.add(backButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
       shoppingScreen.initializeDatas();
       shoppingScreen.revalidate();
       shoppingScreen.repaint();
       shoppingScreen.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
}
