/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;

/**
 *
 * @author onatu
 */
public class productScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(productScreen.class.getName());
    ProductPane productPane;
    boolean inStock;
    Connection conn;
    /**
     * Creates new form productFrame
     */
    public productScreen(shoppingScreen shoppingScreen, ProductPane productPane) {
        initComponents();
        this.productPane = productPane;
        conn=shoppingScreen.conn;
        getStockInfo();
        
        // 1. Ekran boyutunu ve konumunu eski ekrandan birebir kopyala
        //this.setSize(shoppingScreen.getSize());
        this.setLocation(shoppingScreen.getLocation());
        
        // 2. Arayüzdeki (JLabel ve JTextPane) alanları objeden gelen verilerle doldur
        // (ProductPane içindeki nesnenin adı "prodcut" olduğu için o şekilde çağırdık)
        if (productPane.product != null) {
            name.setText(productPane.product.getProductName());
            category.setText(productPane.product.getCategory());
            sku_code.setText(productPane.product.getSku_Code());
            description.setText(productPane.product.getDescription());
            color.setText(productPane.product.getColor());
            size.setText(productPane.product.getSize());
            shade.setText(productPane.product.getShade());
        }

        // 3. İkon ayarlaması (Eğer utilities sınıfınla atamak istersen)
        // utilities util = new utilities();
        // productIcon.setIcon(util.setIconSize(84, 91, "/frames/packageIcon.png"));

        // 4. "Go Back" (Geri Dön) Butonunun Çalışması (jButton1)
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Eski ekranın boyut ve konumunu bu ekranın güncel haline eşitle (Pencereyi kaydırdıysa diye)
                //shoppingScreen.setSize(productScreen.this.getSize());
                shoppingScreen.setLocation(productScreen.this.getLocation());
                
                // Eski ekranı göster, bu ekranı kapat (yok et)
                shoppingScreen.initializeDatas();
                shoppingScreen.revalidate();
                shoppingScreen.repaint();
                shoppingScreen.setVisible(true);
                productScreen.this.dispose();
            }
        });
    }
    
    public void getStockInfo() {
        // Ürün objesi yoksa hata vermemesi için güvenlik kontrolü
        if (productPane.product == null) return;

        // Ürünün benzersiz SKU kodunu alıyoruz
        String skuCode = productPane.product.getSku_Code();
        
        // Veritabanı Sorgusu: O SKU koduna sahip varyantın tüm depolardaki stoklarını topla
        String sql = "SELECT SUM(i.stockQuantity) AS totalStock " +
                     "FROM Inventory i " +
                     "JOIN Product_Variants pv ON i.variantID = pv.variantID " +
                     "WHERE pv.sku_Code = ?";

        // Güvenli sorgu çalıştırmak için PreparedStatement kullanıyoruz
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, skuCode); // Soru işareti olan yere SKU kodunu koy

            try (ResultSet rs = pstmt.executeQuery()) {
                int stock = 0;
                if (rs.next()) {
                    stock = rs.getInt("totalStock"); // Toplam stoğu değişkene ata
                }

                // Stok kontrolü ve Arayüz (UI) Güncellemesi
                if (stock > 0) {
                    stockStatus.setText("In Stock");
                    stockStatus.setForeground(new java.awt.Color(0, 153, 51)); // Yazıyı Yeşil yap
                    addButton.setEnabled(true); // Sepete Ekle butonunu aktifleştir
                } else {
                    stockStatus.setText("Out of Stock");
                    stockStatus.setForeground(new java.awt.Color(204, 0, 0)); // Yazıyı Kırmızı yap
                    addButton.setEnabled(false); // Stok yoksa butonu devre dışı bırak (Tıklanamaz)
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            stockStatus.setText("Stock Error");
            addButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        productIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextPane();
        descriptionLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        sku_codeLabel = new javax.swing.JLabel();
        sku_code = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        stockStatus = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        shadeLabel = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        shade = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productIcon.setText("jLabel1");

        description.setEditable(false);
        jScrollPane1.setViewportView(description);

        descriptionLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        descriptionLabel.setText("Description ");

        categoryLabel.setText("Category:");

        category.setText("toFill");

        sku_codeLabel.setText("sku. code:");

        sku_code.setText("toFill");

        name.setText("toFill");

        nameLabel.setText("Name:");

        stockStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stockStatus.setText("in stock");

        colorLabel.setText("Color:");

        sizeLabel.setText("Size:");

        shadeLabel.setText("Shade:");

        color.setText("jLabel1");

        size.setText("jLabel2");

        shade.setText("jLabel3");

        addButton.setText("add to cart");

        jButton1.setText("go back");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(shadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(category, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(categoryLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sku_codeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sku_code, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jButton1))
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(descriptionLabel)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(43, 43, 43))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stockStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(productIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(categoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(category)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sku_codeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sku_code)
                        .addGap(51, 51, 51)
                        .addComponent(stockStatus))
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLabel)
                    .addComponent(color)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLabel)
                    .addComponent(size))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shadeLabel)
                    .addComponent(shade))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel category;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel color;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextPane description;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel productIcon;
    private javax.swing.JLabel shade;
    private javax.swing.JLabel shadeLabel;
    private javax.swing.JLabel size;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel sku_code;
    private javax.swing.JLabel sku_codeLabel;
    private javax.swing.JLabel stockStatus;
    // End of variables declaration//GEN-END:variables
}
