/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import Database.User;
import Database.dataHolder;

import java.sql.*;
import java.util.ArrayList;

/**
 *
 * @author onatu
 */
public class shoppingScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(shoppingScreen.class.getName());
    Connection conn;
    ArrayList<product> products;
    /**
     * Creates new form shoppingScreen
     */
    public shoppingScreen(loginScreen loginScreen) {
        initComponents();
        this.setLocation(300,0);
        this.setSize(650,800);
        conn = loginScreen.conn;
        products = new ArrayList<>();
        initializeDatas();
    }

    
    public void initializeDatas(){
        gridPanel.removeAll();
        
        // Veritabanı bağlantını sağladığını ve sorguyu çalıştırdığını varsayıyoruz:
        String sql = "SELECT * " +
                "FROM Products p " +
                "join Product_Variants pv ON p.productID=pv.productID " +
                "join Categories c ON p.categoryID=c.categoryID"; // Tablo adın neyse ona göre düzelt

        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            // Veritabanındaki her bir satır (ürün) için dönecek
            while (rs.next()) {
                // 1. Dataları veritabanından al
                int dbId = rs.getInt("productID");
                String dbName = rs.getString("brandName");
                double dbPrice = rs.getDouble("basePrice");
                String dbCategory = rs.getString("categoryName");
                String dbDescription = rs.getString("description");
                String dbColor = rs.getString("color");
                String dbSize = rs.getString("size");
                String dbShade = rs.getString("shade");
                String dbsku_Code = rs.getString("sku_Code");

                // 2. Bu datalarla YENİ BİR OBJE yarat (ProductPane)
                ProductPane yeniUrunObjesi = new ProductPane(dbId, dbName, dbPrice, dbCategory, dbDescription, dbColor, dbSize, dbShade, dbsku_Code);
                product product = new product(dbId, dbName, dbCategory, dbPrice, dbDescription, dbColor, dbSize, dbShade, dbsku_Code);
                products.add(product);
                dataHolder.products.add(product);
                yeniUrunObjesi.product =product;
                System.out.println("product added to arraylist: " + dataHolder.findProductById(dbId));

                // 3. Yarattığın bu yeni objeyi arayüzdeki ana panele ekle
                gridPanel.add(yeniUrunObjesi);

            }

            // İşlem bitince ekrandaki güncellemeyi göster
            gridPanel.revalidate();
            gridPanel.repaint();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        shoppingLabel = new javax.swing.JLabel();
        ordersButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        gridPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shoppingLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        shoppingLabel.setForeground(new java.awt.Color(255, 51, 255));
        shoppingLabel.setText("Shopping");

        ordersButton.setText("Orders");
        ordersButton.addActionListener(this::ordersButtonActionPerformed);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shoppingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(ordersButton)
                .addGap(28, 28, 28))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shoppingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordersButton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        gridPanel.setLayout(new java.awt.GridLayout(0, 4));
        scrollPane.setViewportView(gridPanel);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersButtonActionPerformed
        if(User.getRole().toLowerCase().equals("customer")){
        ordersScreenCustomer os_Customer=new ordersScreenCustomer(conn,this);
        os_Customer.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_ordersButtonActionPerformed

    /**
     * @param args the command line arguments
     */

//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gridPanel;
    private javax.swing.JButton ordersButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel shoppingLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
